[project]
name = "fed-deep-clustering"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "flwr[simulation]>=1.29.0",
    "flwr-datasets[vision]>=0.6.0",
    "matplotlib>=3.10.9",
    "notebook>=7.5.5",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "optuna>=3.6.0",
    "optuna-integration[wandb]>=3.6.0",
    "plotly>=5.0.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.11.0",
    "wandb>=0.17.0",
    "seaborn>=0.13.2",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "fed_dcn_synthetic_app"
module-root = "fed-dcn-synthetic"

